# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .nx/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-angular-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-angular-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test --if-present
      - name: zip artifact all
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: zip all.zip ./* -r
      - name: Upload artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: web.zip
          retention-days: 60
